package fr.cgi.magneto.realtime;

public enum MagnetoMessageType {
    connection,
    connectedUsers,
    disconnection,
    ping,
    boardUpdated,
    cardAdded,
    cardEditionStarted,
    cardUpdated,
    cardEditionEnded,
    cardMoved,
    cardsBoardUpdated,
    cardsDeleted,
    cardFavorite,
    sectionUpdated,
    sectionsUpdated,
    sectionAddedWithCard,
    commentAdded,
    commentDeleted,
    commentEdited,
    cardDuplicated,
    sectionDuplicated,
    sectionAdded,
    sectionsDeleted,
    boardMessage,
    cardEditing,
}
