export enum WEBSOCKET_MESSAGE_TYPE {
  BOARD_UPDATED = "boardUpdated",
  CARD_ADDED = "cardAdded",
  CARD_FAVORITE = "cardFavorite",
  COMMENT_ADDED = "commentAdded",
  COMMENT_EDITED = "commentEdited",
  COMMENT_DELETED = "commentDeleted",
  CARD_UPDATED = "cardUpdated",
  CARDS_DELETED = "cardsDeleted",
  SECTION_UPDATED = "sectionUpdated",
  SECTIONS_UPDATED = "sectionsUpdated",
  CARD_DUPLICATED = "cardDuplicated",
  SECTION_DUPLICATED = "sectionDuplicated",
  SECTION_ADDED = "sectionAdded",
  SECTIONS_DELETED = "sectionsDeleted",
  CARD_MOVED = "cardMoved",
  CARDS_BOARD_UPDATED = "cardsBoardUpdated",
  BOARD_MESSAGE = "boardMessage",
  CARD_EDITION_STARTED = "cardEditionStarted",
  CARD_EDITION_ENDED = "cardEditionEnded",
  SECTION_ADDED_WITH_CARD = "sectionAddedWithCard",
}

export const MESSAGE_TYPE_TO_I18N_KEY: Record<string, string> = {
  [WEBSOCKET_MESSAGE_TYPE.BOARD_UPDATED]: "",
  [WEBSOCKET_MESSAGE_TYPE.CARD_ADDED]: "",
  [WEBSOCKET_MESSAGE_TYPE.CARD_FAVORITE]: "",
  [WEBSOCKET_MESSAGE_TYPE.COMMENT_ADDED]: "",
  [WEBSOCKET_MESSAGE_TYPE.COMMENT_EDITED]: "",
  [WEBSOCKET_MESSAGE_TYPE.COMMENT_DELETED]: "",
  [WEBSOCKET_MESSAGE_TYPE.CARD_UPDATED]: "",
  [WEBSOCKET_MESSAGE_TYPE.CARDS_DELETED]: "magneto.delete.card.confirm",
  [WEBSOCKET_MESSAGE_TYPE.SECTION_UPDATED]: "magneto.update.section.confirm",
  [WEBSOCKET_MESSAGE_TYPE.SECTIONS_UPDATED]: "",
  [WEBSOCKET_MESSAGE_TYPE.CARD_DUPLICATED]: "magneto.duplicate.cards.confirm",
  [WEBSOCKET_MESSAGE_TYPE.SECTION_DUPLICATED]:
    "magneto.duplicate.section.confirm",
  [WEBSOCKET_MESSAGE_TYPE.SECTION_ADDED]: "magneto.create.section.confirm",
  [WEBSOCKET_MESSAGE_TYPE.SECTIONS_DELETED]: "",
  [WEBSOCKET_MESSAGE_TYPE.CARD_MOVED]: "",
  [WEBSOCKET_MESSAGE_TYPE.CARDS_BOARD_UPDATED]: "",
  [WEBSOCKET_MESSAGE_TYPE.SECTION_ADDED_WITH_CARD]: "",
};
